//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZSave.GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EZSave.GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your choice :.
        /// </summary>
        public static string ChoiceTitle {
            get {
                return ResourceManager.GetString("ChoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Press any key to continue ....
        /// </summary>
        public static string ChooseChoiceTitle {
            get {
                return ResourceManager.GetString("ChooseChoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Config file path : .
        /// </summary>
        public static string ConfigFilePathChanging {
            get {
                return ResourceManager.GetString("ConfigFilePathChanging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        public static string ConfigOption1 {
            get {
                return ResourceManager.GetString("ConfigOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update.
        /// </summary>
        public static string ConfigOption2 {
            get {
                return ResourceManager.GetString("ConfigOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete a job.
        /// </summary>
        public static string ConfigOption3 {
            get {
                return ResourceManager.GetString("ConfigOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change log destination path.
        /// </summary>
        public static string ConfigOption4 {
            get {
                return ResourceManager.GetString("ConfigOption4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change config destination path.
        /// </summary>
        public static string ConfigOption5 {
            get {
                return ResourceManager.GetString("ConfigOption5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change status destination path.
        /// </summary>
        public static string ConfigOption6 {
            get {
                return ResourceManager.GetString("ConfigOption6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Go back to main menu.
        /// </summary>
        public static string ConfigOption7 {
            get {
                return ResourceManager.GetString("ConfigOption7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration mode.
        /// </summary>
        public static string ConfModeTitle {
            get {
                return ResourceManager.GetString("ConfModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CryptoKey.
        /// </summary>
        public static string CryptoKey {
            get {
                return ResourceManager.GetString("CryptoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the job to delete : .
        /// </summary>
        public static string EnterDeletedJob {
            get {
                return ResourceManager.GetString("EnterDeletedJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job destination : .
        /// </summary>
        public static string EnterDestination {
            get {
                return ResourceManager.GetString("EnterDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job name : .
        /// </summary>
        public static string EnterJobName {
            get {
                return ResourceManager.GetString("EnterJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the job to modify : .
        /// </summary>
        public static string EnterModifiedJob {
            get {
                return ResourceManager.GetString("EnterModifiedJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job source : .
        /// </summary>
        public static string EnterSource {
            get {
                return ResourceManager.GetString("EnterSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job backup type : .
        /// </summary>
        public static string EnterType {
            get {
                return ResourceManager.GetString("EnterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execute all.
        /// </summary>
        public static string ExecuteAllJobs {
            get {
                return ResourceManager.GetString("ExecuteAllJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execute one.
        /// </summary>
        public static string ExecuteOneJob {
            get {
                return ResourceManager.GetString("ExecuteOneJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File Size to upload.
        /// </summary>
        public static string FileSizeThreshold {
            get {
                return ResourceManager.GetString("FileSizeThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid choice. Try again..
        /// </summary>
        public static string InvalidChoiceTitle {
            get {
                return ResourceManager.GetString("InvalidChoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The job has been added !.
        /// </summary>
        public static string JobAdded {
            get {
                return ResourceManager.GetString("JobAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The job has been deleted !.
        /// </summary>
        public static string JobDeleted {
            get {
                return ResourceManager.GetString("JobDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Destination.
        /// </summary>
        public static string JobDestination {
            get {
                return ResourceManager.GetString("JobDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The job has been edited !.
        /// </summary>
        public static string JobEdited {
            get {
                return ResourceManager.GetString("JobEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job edition space : .
        /// </summary>
        public static string JobEdition {
            get {
                return ResourceManager.GetString("JobEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        public static string JobName {
            get {
                return ResourceManager.GetString("JobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The job has not been added !.
        /// </summary>
        public static string JobNotAdded {
            get {
                return ResourceManager.GetString("JobNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The job has not been deleted !.
        /// </summary>
        public static string JobNotDeleted {
            get {
                return ResourceManager.GetString("JobNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jobs execution failed !.
        /// </summary>
        public static string JobsExecutedFail {
            get {
                return ResourceManager.GetString("JobsExecutedFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jobs executed with success !.
        /// </summary>
        public static string JobsExecutedSuccess {
            get {
                return ResourceManager.GetString("JobsExecutedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source.
        /// </summary>
        public static string JobSource {
            get {
                return ResourceManager.GetString("JobSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup type.
        /// </summary>
        public static string JobType {
            get {
                return ResourceManager.GetString("JobType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à French.
        /// </summary>
        public static string LanguageOption1 {
            get {
                return ResourceManager.GetString("LanguageOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English.
        /// </summary>
        public static string LanguageOption2 {
            get {
                return ResourceManager.GetString("LanguageOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Launch server.
        /// </summary>
        public static string LaunchServer {
            get {
                return ResourceManager.GetString("LaunchServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jobs that can be deleted : .
        /// </summary>
        public static string ListJobsPossibleDelete {
            get {
                return ResourceManager.GetString("ListJobsPossibleDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jobs thtat can be modified : .
        /// </summary>
        public static string ListJobsPossibleModify {
            get {
                return ResourceManager.GetString("ListJobsPossibleModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logs path : .
        /// </summary>
        public static string LogPathChanging {
            get {
                return ResourceManager.GetString("LogPathChanging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log type (xml/json) :.
        /// </summary>
        public static string LogTypeChanging {
            get {
                return ResourceManager.GetString("LogTypeChanging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Main menu :.
        /// </summary>
        public static string MainMenuTitle {
            get {
                return ResourceManager.GetString("MainMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execute jobs.
        /// </summary>
        public static string MainOption1 {
            get {
                return ResourceManager.GetString("MainOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter in config mode.
        /// </summary>
        public static string MainOption2 {
            get {
                return ResourceManager.GetString("MainOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change language.
        /// </summary>
        public static string MainOption3 {
            get {
                return ResourceManager.GetString("MainOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refresh.
        /// </summary>
        public static string RefreshJobs {
            get {
                return ResourceManager.GetString("RefreshJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Resume.
        /// </summary>
        public static string ResumeJob {
            get {
                return ResourceManager.GetString("ResumeJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Status file path : .
        /// </summary>
        public static string StatusFilePathChanging {
            get {
                return ResourceManager.GetString("StatusFilePathChanging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jobs ready to be executed : .
        /// </summary>
        public static string TitleListBox {
            get {
                return ResourceManager.GetString("TitleListBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validate.
        /// </summary>
        public static string Validate {
            get {
                return ResourceManager.GetString("Validate", resourceCulture);
            }
        }
    }
}
